logging:
  mode: offline
  project: cellvit++
  notes: cellvit++
  log_comment: cellvit++
  wandb_dir: ./logs_local
  log_dir: ./logs_local
  level: Debug

sweep:
  method: bayes
  name: experimental_sweep
  metric:
    goal: maximize
    name: AUROC/Validation
  run_cap: 100


random_seed: 19

gpu: 0

data:
  dataset: SegmentationDataset
  dataset_path: ./test_database/training_database/Example-Segmentation
  normalize_stains_train: false
  normalize_stains_val: false
  num_classes: 4
  train_filelist: ./test_database/training_database/Example-Segmentation/splits/fold_0/train.csv
  val_filelist: ./test_database/training_database/Example-Segmentation/splits/fold_0/val.csv
  label_map:
    1: "Non-Tumor"
    2: "Tumor"

cellvit_path: ./checkpoints/CellViT-256-x40-AMP.pth

model:
  parameters:
    hidden_dim:
      values: [128, 256, 512]

training:
  cache_cell_dataset: true
  batch_size: 64
  epochs: 50
  drop_rate: 0.1
  optimizer: AdamW
  optimizer_hyperparameter:
    betas: [0.85, 0.9]
    parameters:
      lr:
        min: 0.00001
        max: 0.01
      weight_decay:
        min: 0.00001
        max: 0.001
  early_stopping_patience: 20
  scheduler:
    parameters:
      scheduler_type:
        values: [constant, exponential]
  mixed_precision: true
  eval_every: 1
